<option value="Business, industry and consumers">
<option value="Culture, media and sport">
<option value="Education">
<option value="Employment and training">
<option value="Parliament, government and politics">
<option value="London">
<option value="Wales">
<option value="China">
<option value="France">
<option value="Kenya">
<option value="Russia">
<option value="USA">
<option value="No stated interests.">
<option value="Communities and families">
<option value="Health services and medicine">
<option value="Housing and planning">
<option value="Science and technology">
<option value="Social services">
<option value="Asylum, immigration and nationality">
<option value="Crime, civil law, justice and rights">
<option value="International affairs">
<option value="Islam">
<option value="Women">
<option value="India">
<option value="Middle East">
<option value="The Commonwealth">
<option value="Economy and finance">
<option value="European Union">
<option value="Faith and integration">
<option value="The United Nations">
<option value="Hampshire">
<option value="Scotland">
<option value="Surrey">
<option value="Australia">
<option value="Indian Sub Continent">
<option value="Middle East (MENA)">
<option value="Turkey">
<option value="United States">
<option value="Greater Manchester">
<option value="Lancashire">
<option value="Midlands">
<option value="Yorkshire">
<option value="Europe">
<option value="North Africa">
<option value="South Asia">
<option value="Digital">
<option value="Third Sector">
<option value="Energy and environment">
<option value="Social security and pensions">
<option value="Social Services">
<option value="Ethical issues">
<option value="Freedom of religion and belief">
<option value="Human rights">
<option value="The North West, particularly Merseyside and Lancashire">
<option value="East Asia">
<option value="Equatorial Africa">
<option value="The Middle East">
<option value="National security">
<option value="East Anglia">
<option value="Former Soviet Union">
<option value="Defence">
<option value="Africa">
<option value="Central Europe">
<option value="Middle-East">
<option value="">
<option value="International Affairs">
<option value="Kurdistan">
<option value="Housing and planning (Homelessness)">
<option value="Vulnerable and excluded people">
<option value="North East of England">
<option value="Africa, particularly East Africa">
<option value="Europe, particularly Spain">
<option value="Agriculture, animals, food and rural affairs">
<option value="Kent">
<option value="ASEAN">
<option value="Belgium">
<option value="Gulf Area">
<option value="Prison reform">
<option value="Transport">
<option value="Skills Training">
<option value="North East England">
<option value="South East England">
<option value="Demographics">
<option value="Housing the old">
<option value="Retirement">
<option value="North-West England">
<option value="Japan">
<option value="Equalities">
<option value="Gypsies, Roma and travellers">
<option value="Local Government">
<option value="South West">
<option value="Trade Unions">
<option value="Cambridge">
<option value="South London">
<option value="British Commonwealth">
<option value="North Cyprus">
<option value="HIV">
<option value="LGBT rights and equality">
<option value="Population development and reproductive health">
<option value="Social enterprise and the voluntary sector">
<option value="Southern Africa">
<option value="Taiwan">
<option value="Western Balkans">
<option value="Child protection and safeguarding">
<option value="Domestic violence and abuse">
<option value="India, USA">
<option value="Education, policing, criminal justice system">
<option value="International development">
<option value="North-East England">
<option value="Local government">
<option value="Israel">
<option value="UK's relationship with its Crown Dependencies (Channel Islands & Isle of Man)">
<option value="Northumberland">
<option value="Canada">
<option value="Scandinavia">
<option value="Cornwall">
<option value="Cumbria">
<option value="Devon">
<option value="Caribbean">
<option value="East Midlands">
<option value="Rutland">
<option value="Commonwealth">
<option value="Ghana">
<option value="Trinidad">
<option value="Disability">
<option value="Pre-natal and post natal care">
<option value="Ageing and older people">
<option value="Dorset">
<option value="North Yorkshire">
<option value="Libel Law">
<option value="Northern Ireland">
<option value="Ireland">
<option value="Pakistan">
<option value="United Kingdom">
<option value="Cambridgeshire">
<option value="Oxfordshire">
<option value="Merseyside">
<option value="South Africa">
<option value="Climate Change">
<option value="Northamptonshire">
<option value="Suffolk Coastal">
<option value="Brussels">
<option value="Future generations">
<option value="Literacy">
<option value="Poverty prevention">
<option value="Social business">
<option value="Notting Hill (Kensington and Chelsea)">
<option value="City of Westminster">
<option value="Greater London">
<option value="Edinburgh (Lothian)">
<option value="Cardiff (South Glamorgan)">
<option value="Democratic Republic of Congo">
<option value="Malawi">
<option value="Liverpool">
<option value="Gulf States">
<option value="Animal Welfare">
<option value="Equality Issues">
<option value="Essex">
<option value="Italy">
<option value="Health service and medicine">
<option value="Rwanda, Democratic Republic of Congo, Sudan, Afghanistan, Iran, colombia, Africa Great Lakes Region">
<option value="Civil liberties and human rights, home affairs, international development, universities, science, environment, women, peace and security">
<option value="Charities/voluntary sector">
<option value="Civil Society/The voluntary and community sector">
<option value="Security (including cyber security)">
<option value="Sheffield">
<option value="France, USA">
<option value="Constitutional">
<option value="Warwickshire">
<option value="Indian subcontinent">
<option value="South East Asia">
<option value="Caucasus">
<option value="East Sussex">
<option value="Isle of Wight">
<option value="The North West">
<option value="Hong Kong">
<option value="North America">
<option value="Policing">
<option value="Almost all areas of the UK, including Edinburgh and Belfast">
<option value="Cumbria - Lake District (particular)">
<option value="North of England (general)">
<option value="Home Affairs">
<option value="County Down and Northern Ireland">
<option value="Greece">
<option value="Human trafficking">
<option value="Modern slavery">
<option value="Diocese of Bristol">
<option value="City of Bristol">
<option value="North Wiltshire">
<option value="South Gloucestershire">
<option value="Swindon">
<option value="Energy and Environment">
<option value="Financial education">
<option value="EU">
<option value="Road safety">
<option value="Climate change, mitigation and adaption">
<option value="West Midlands">
<option value="Vietnam">
<option value="Croatia">
<option value="Montenegro">
<option value="Serbia">
<option value="Science and Technology">
<option value="Euro-Atlantic Area">
<option value="Azerbaijan">
<option value="Russian Federation">
<option value="Consumer protection & Regulation">
<option value="The Environment and Climate Change">
<option value="Financial Services">
<option value="Police and Security">
<option value="Constitutional affairs">
<option value="Baltic States, Canada, Eastern Europe, Scandinavia, USA, developing countries">
<option value="Energy, gas industry, oil industry, industrial policy, trade policy, deaf children, Scottish home rule and federalism">
<option value="Creative industries">
<option value="Early years">
<option value="Equal opportunities">
<option value="Immigration policy">
<option value="Obesity and eating disorders">
<option value="Social mobility">
<option value="Socio-economic and other diversities">
<option value="Brecon (Powys, Wales)">
<option value="Women's policy issues">
<option value="Prison issues">
<option value="Guinea-Bissau, Papua New Guinea, Bangladesh">
<option value="Intelligence issues">
<option value="Children and family law">
<option value="West Country particularly Devon">
<option value="Gibraltar">
<option value="Overseas development">
<option value="South West of England">
<option value="Sub Saharan Africa">
<option value="Sport">
<option value="Sweden">
<option value="The Lake District">
<option value="Iceland">
<option value="Ethics">
<option value="Mediation">
<option value="Reconciliation">
<option value="Diocese of Durham">
<option value="Diocese of Liverpool">
<option value="Diosese of Coventry">
<option value="Nigeria">
<option value="Faith and Religion">
<option value="Cheshire">
<option value="Wiltshire">
<option value="N. Argentina">
<option value="Norway">
<option value="Buckinghamshire">
<option value="Milton Keynes">
<option value="Lincolnshire">
<option value="Middle East - Saudi Arabia">
<option value="Far East - China and Hong Kong">
<option value="LGBT+ rights">
<option value="Gambling policy">
<option value="Addiction">
<option value="Foreign Affairs, especially the Balkans and Eastern Europe">
<option value="Environment">
<option value="Archaeology and heritage">
<option value="Anglo-American relations">
<option value="East London">
<option value="Trinidad and Tobago">
<option value="North East">
<option value="North Norfolk">
<option value="South East">
<option value="UK">
<option value="North West">
<option value="Egypt">
<option value="South America">
<option value="North of England">
<option value="Australia/New Zealand">
<option value="Digital, technology and artificial intelligence">
<option value="Intellectual property">
<option value="Urban regeneration">
<option value="South Yorkshire">
<option value="Wales (particularly North Wales)">
<option value="Germany">
<option value="Diabetes">
<option value="Spain">
<option value="Bermuda">
<option value="Latin America">
<option value="Gloucestershire">
<option value="Somerset">
<option value="West of England">
<option value="Jordan">
<option value="Lebanon">
<option value="Palestine">
<option value="Maritime affairs">
<option value="Sussex">
<option value="Australasia">
<option value="Netherlands">
<option value="Staffordshire">
<option value="Finland">
<option value="Women in the Criminal Justice System">
<option value="Bristol">
<option value="West Country">
<option value="Switzerland">
<option value="Modern languages">
<option value="Chile">
<option value="Peru">
<option value="Small businesses">
<option value="Ethics of beginning and end of life">
<option value="Freedom of Religion and Belief">
<option value="Coventry">
<option value="Iraq">
<option value="Syria">
<option value="Gender discrimination">
<option value="Human rights and humanitarian aid">
<option value="Slavery and human trafficking">
<option value="Myanmar">
<option value="South Sudan">
<option value="Sudan">
<option value="Holland">
<option value="Culture, Media and Sport">
<option value="Global health">
<option value="Central Asia">
<option value="Russia, Caucasus and C.I.S.">
<option value="County Durham">
<option value="Military veterans and Service charities">
<option value="Norfolk">
<option value="Afghanistan">
<option value="Nepal">
<option value="Transport, education, health, economic policy, constitution">
<option value="Global health policy">
<option value="Far East">
<option value="Enfield">
<option value="Michigan, USA">
<option value="Sri Lanka">
<option value="Asia">
<option value="South West England">
<option value="Suffolk">
<option value="Family law">
<option value="Regulation of legal services">
<option value="Reproductive technology">
<option value="Oxford">
<option value="Poland">
<option value="Development">
<option value="Gender">
<option value="Poverty">
<option value="International Development">
<option value="Crime, civil law, justice and rights, Culture, media and sport">
<option value="Diversity">
<option value="Race issues">
<option value="Indian Sub-continent">
<option value="Health and Safety in Construction">
<option value="Teacher Training">
<option value="Standards in Public Life">
<option value="Occupational Pensions">
<option value="Health and Social Care">
<option value="Child trafficking">
<option value="Children">
<option value="International aid and development">
<option value="South Korea">
<option value="LGBT">
<option value="EU, USA">
<option value="West Sussex">
<option value="NE England">
<option value="Rwanda">
<option value="Burundi">
<option value="Lesotho">
<option value="Iran">
<option value="Communities and Families">
<option value="Devolved administrations">
<option value="Arts and Culture">
<option value="Eastern Europe">
<option value="Dwyfor Meirionnydd, Llyn Area of Outstanding Natural Beauty">
<option value="Snowdonia National Park">
<option value="Zimbabwe">
<option value="Romania">
<option value="South India">
<option value="Armed Forces/Defence">
<option value="Artificial intelligence (social and economic effects)">
<option value="Dignity in Dying">
<option value="Exiting the European Union">
<option value="Homelessness">
<option value="Mental health">
<option value="Polar Regions">
<option value="Shipping/Maritime Affairs (Including marine insurance and law)">
<option value="Transport (particularly motorcycling)">
<option value="Countries of Former Soviet Union">
<option value="Hampshire (farming)">
<option value="Sub-Saharan Africa">
<option value="Constitution">
<option value="The Arts">
<option value="Film and television">
<option value="Public Service reform">
<option value="Ageing society and its opportunities">
<option value="Medical Ethics">
<option value="Women and development">
<option value="Family planning">
<option value="Assisted dying">
<option value="Negative impact of Sharia law">
<option value="Social Security and pensions">
<option value="Animal welfare">
<option value="Horticulture and related subjects">
<option value="The West Country, especially Plymouth">
<option value="Indonesia">
<option value="New Zealand">
<option value="International Aid & Development">
<option value="Bath">
<option value="Ayrshire">
<option value="Edinburgh">
<option value="Shropshire">
<option value="Heredfordshire">
<option value="Bangladesh">
<option value="Singapore">
<option value="Thailand">
<option value="East Kent">
<option value="Health services and medicines">
<option value="Women rights">
<option value="Equality for women">
<option value="Promote women in political and public life">
<option value="South-East Asia">
<option value="Agriculture, defence, foreign affairs, education, constitutional affairs">
<option value="Moldova">
<option value="Slovenia">
<option value="US">
<option value="Cuba">
<option value="Campaign to legalise assisted dying">
<option value="Cinema and Theatre">
<option value="Scottish affairs">
<option value="Tourism">
<option value="Glasgow">
<option value="South Pacific">
<option value="UAE">
<option value="Environment, democratic reform">
<option value="Empowerment of women and girls (global)">
<option value="Women, Peace and Security">
<option value="Women at the Peace Table">
<option value="Women's Economic Leadership and Business">
<option value="Banking">
<option value="Education (Higher Education)">
<option value="Financial regulation">
<option value="Manchester">
<option value="Denmark">
<option value="Pennine Lancashire">
<option value="Scottish Highlands and Islands">
<option value="Bosnia-Herzegovina">
<option value="Pyrenees">
<option value="Christian persecution">
<option value="Ageing and intergenerational issues">
<option value="Disability rights">
<option value="Public transport">
<option value="Religion">
<option value="Civil society">
<option value="Haiti">
<option value="Cambodia">
<option value="West Africa">
<option value="Sierra Leone">
<option value="Gambia">
<option value="South Wales">
<option value="Agriculture, economic policy">
<option value="Middle East: South Africa">
<option value="Theatre">
<option value="Galloway">
<option value="United Nations">
<option value="Energy and the environment">
<option value="Home Counties">
<option value="Digital economy and digital social issues">
<option value="Overseas aid">
<option value="West Wales">
<option value="Georgia">
<option value="West Papua">
<option value="Charities">
<option value="Security">
<option value="Tourism and hospitality">
<option value="English Lake District">
<option value="Humber">
<option value="Nothern Ireland">
<option value="Northern Powerhouse">
<option value="Defence and the Royal Navy">
<option value="East Lancashire">
<option value="Highlands and Islands">
<option value="Kyrgyzstan">
<option value="Global Health">
<option value="Labour history">
<option value="Industrial relations">
<option value="Women and equality">
<option value="Plastics">
<option value="Women's Rights">
<option value="Domestic violence policy">
<option value="Preventing Sexual Violence in Conflict Initiative (PSVI)">
<option value="Women peace and security">
<option value="Policing at both national and local level">
<option value="North West England">
<option value="Devolution">
<option value="Ukraine">
<option value="The Caucasus">
<option value="International women's issues">
<option value="Gender and equality">
<option value="Women in conflict">
<option value="Foreign affairs">
<option value="Business, industry and city">
<option value="Charities and civil society">
<option value="Prisons, civil law, justice and rights">
<option value="UK's demographic future">
<option value="Oman">
<option value="Press regulation">
<option value="North East and South East Asia">
<option value="North West of England">
<option value="Education and Children">
<option value="Health">
<option value="Youth justice">
<option value="Chilterns">
<option value="Republic of Korea">
<option value="Commonwealth affairs">
<option value="International energy issues">
<option value="Pacific Rim">
<option value="Civil service">
<option value="Conflicts - prevention, mediation and resolution">
<option value="Crime, civil law, justice and human rights">
<option value="European affairs">
<option value="Social security and safety net">
<option value="South East Europe">
<option value="Northern England">
<option value="The digital economy">
<option value="Philanthropy">
<option value="EU Countries">
<option value="Southern and East Africa">
<option value="Agriculture, food and rural affairs">
<option value="Civil liberties">
<option value="Climate change and protection of the environment">
<option value="Newcastle">
<option value="Portsmouth">
<option value="Solent">
<option value="Global">
<option value="The constitution">
<option value="Malta">
<option value="The Gulf">
<option value="United States of America">
<option value="Saudi Arabia">
<option value="East of England">
<option value="International human rights development">
<option value="Southern Ireland">
<option value="Children's rights">
<option value="United Nations organisation">
<option value="Pacific Islands">
<option value="Western Europe">
<option value="Scottish Borders">
<option value="Iraq and other MENA area countries">
<option value="Digital policy">
<option value="The West Country">
<option value="Western Highlands">
<option value="Mauritania">
<option value="Central and Eastern Europe">
<option value="Business and industry">
<option value="Constitutional matters">
<option value="Surrey and Hampshire">
<option value="North America Pacific">
<option value="Europe (esp. Germany, Russia)">
<option value="Central Asia (esp. Kazakhstan)">
<option value="Africa (esp. Sudan, Tanzania, Zimbabwe)">
<option value="Fife">
<option value="Voluntary and charitable sector">
<option value="Foreign Affairs in particular, the Middle East">
<option value="Gay rights">
<option value="South East Asia and Pacific">
<option value="Israel/Palestine">
<option value="Economic policy">
<option value="Better Regulation">
<option value="Accreditation">
<option value="Honours System">
<option value="Conservation">
<option value="Restoration">
<option value="Inequality">
<option value="Nordic countries">
<option value="Economy and Finance">
<option value="Humanitarian causes">
<option value="International development aid projects">
<option value="Gabon">
<option value="Security and intelligence">
<option value="Access to legal services">
<option value="Assistive technology">
<option value="Neighbour disputes">
<option value="Property and construction">
<option value="Exmoor">
<option value="Austria">
<option value="Scotland (the Highlands in particular)">
<option value="Aids to navigation">
<option value="Nursing">
<option value="Falkland Islands">
<option value="Exmoor National Park">
<option value="Small businesses, training, economic regeneration, sport, drugs">
<option value="Asylum, immigration, and nationality">
<option value="Portugal">
<option value="HIV and TB in developing countries in Africa, Asia and Europe">
<option value="Children and young people">
<option value="North West - particularly Lancashire">
<option value="South East - particularly Sussex">
<option value="Central Africa - particularly Kazakhstan">
<option value="Europe - particularly France">
<option value="Cotswolds">
<option value="The obesity epidemic">
<option value="Overseas medical aid">
<option value="Conflict and development">
<option value="Equality and multiculturalism">
<option value="Northern America">
<option value="Agriculture, health, elderly issues, environment, special needs education, planning">
<option value="Equality and diversity in business">
<option value="Economy and training">
<option value="Eastern region">
<option value="Nuclear industry">
<option value="Columbia">
<option value="Guatemala">
<option value="Mexico">
<option value="Children's issues">
<option value="The labour market">
<option value="West and Central Scotland">
<option value="Constitutional Affairs">
<option value="Malaysia">
<option value="Business, manufacturing, economy, higher education, mental health, railways, heritage railways">
<option value="North west England">
<option value="East and West Midlands">
<option value="Jamaica and the Caribbean">
<option value="Wine industry">
<option value="Cayman Islands">
<option value="South America - Chile">
<option value="South East Asia - India, Maldives, Sri Lanka">
<option value="Culture media and sport">
<option value="End of life issues">
<option value="Mental Health, Science and technology">
<option value="Roll out of broadband">
<option value="Vocational education">
<option value="Economic/Fiscal policy">
<option value="European Union.">
<option value="Caribbean.">
<option value="Botswana">
<option value="Cyprus">
<option value="America">
<option value="East Yorkshire">
<option value="Kingston-upon-Thames">
<option value="West Yorkshire">
<option value="Africa - Ethiopia, South Africa and Zimbabwe">
<option value="Performing and visual arts">
<option value="Freedom of religion">
<option value="Smoking and health">
<option value="Mainland Europe">
<option value="Behaviour Change">
<option value="Well-being">
<option value="Warwick">
<option value="Berkshire">
<option value="St Lucia">
<option value="International affairs: Small and Medium Sized Enterprises (SME's)">
<option value="Hertfordshire">
<option value="Mental Health">
<option value="Illegal drug use">
<option value="Yorkshire (Bradford)">
<option value="Derbyshire">
<option value="Northants">
<option value="Peterborough">
<option value="Korea (North and South)">
<option value="Bhutan">
<option value="Qatar">
<option value="Eastern Europe, India, Poland, USA">
<option value="Housing, health, social services, local and regional government">
<option value="Charities and voluntary sector">
<option value="Channel Islands">
<option value="East Africa">
<option value="SE Hampshire">
<option value="Black Country">
<option value="Diversity and equal opportunities">
<option value="South East Scotland">
<option value="Rural affairs">
<option value="Education, housing, social security, health, economic policy, equal opportunities">
<option value="Equalities issues">
<option value="West and Central Europe">
<option value="Commonwealth countries">
<option value="Middle East and Gulf">
<option value="Cultural Affairs">
<option value="Prisons policy">
<option value="Regional Policy (especially North East England)">
<option value="Modern Slavery">
<option value="Universities/Higher Education">
<option value="Uganda">
<option value="Brazil">
<option value="Bulgaria">
<option value="Richmond upon Thames">
<option value="Greenland">
<option value="Lithuania">
<option value="N. Caucasus">
<option value="Local Government Finance">
<option value="East Riding of Yorkshire">
<option value="North and North East Lincolnshire">
<option value="Security and cyber">
<option value="Heath services and medicine">
<option value="International democracy building and human rights">
<option value="Africa (Sub-Saharan)">
<option value="Middle East and North Africa (MENA), North America">
<option value="South West Asia">
<option value="Europe (particularly France)">
<option value="Belgium, France">
<option value="Health, environment, Europe, provision facilities for the young, economy, regional development">
<option value="Africa, Indian sub-continent, Middle East">
<option value="International development, environment, transport, defence, Northern Ireland">
<option value="Wales and the rest of the UK">
<option value="East Europe">
<option value="Outer London (S. East)">
<option value="Estonia">
<option value="Tanzania">
<option value="Architecture">
<option value="Art">
<option value="Urban Regeneration">
<option value="New York">
<option value="Aviation">
<option value="Economic Development">
<option value="Inward and outward Investment">
<option value="Culture and the performing arts">
<option value="Graduate education">
<option value="China (including Hong Kong)">
<option value="North Korea">
<option value="Central South America">
<option value="Forest of Dean">
<option value="Religion and Society">
<option value="Religious extremism">
<option value="North America (particularly the USA), Middle East (particularly Israel)">
<option value="Voluntary sector">
<option value="Bournemouth">
<option value="Poole">
<option value="Latvia">
<option value="South Sudan and Sudan">
<option value="Arts and heritage">
<option value="West Dorset">
<option value="Huntingdon, Cambridge">
<option value="Abu Dhabi">
<option value="Royal Mail">
<option value="Teesside">
<option value="Durham">
<option value="Baltic States">
<option value="Human rights issues in Bahrain">
<option value="IT - Civil Liberties">
<option value="LGBT - Immigration and asylum">
<option value="Teeside">
<option value="Southern Africa - Botswana">
<option value="South East Asia - Malaysia">
<option value="Middle East - Bahrain">
<option value="Crime, media and sport">
<option value="International trade and investment">
<option value="Space">
<option value="Health technology and research">
<option value="House of Lords reform">
<option value="Commonwealth, HM realms, dependent territories and overseas territories">
<option value="Russian and the former Soviet Union">
<option value="Employment">
<option value="Social security">
<option value="Artificial Intelligence">
<option value="Digital Economy">
<option value="Drug discovery and health technology">
<option value="Intelligence and Cyber Security">
<option value="Internet harms and crimes">
<option value="Internet safety">
<option value="Technology">
<option value="Housing and Planning">
<option value="The Midlands">
<option value="Police">
<option value="Russia and former Soviet countries">
<option value="European neighbourhood">
<option value="Asia (India/China)">
<option value="Inter-Church relations">
<option value="Religious freedom">
<option value="East Surrey">
<option value="Bedfordshire">
<option value="Belize">
<option value="Guyana">
<option value="Stoke-on-Trent">
<option value="North East Scotland">
<option value="Anti-corruption and tax evasion">
<option value="Business, industry and finance">
<option value="Culture and media">
<option value="Bees">
<option value="Property compensation">
<option value="Laos">
<option value="NW">
<option value="Civil rights">
<option value="Privacy">
<option value="Constitutional matters in the UK">
<option value="Space Science">
<option value="Third World Development">
<option value="Africa, European Union">
<option value="European Economic Area">
<option value="Promotion of learning foreign languages">
<option value="Indian Subcontinent">
<option value="North Africa/Maghreb">
<option value="Russia and Former Soviet Republics">
<option value="Developing countries">
<option value="Lincoln">
<option value="BRICS">
<option value="Birmingham">
<option value="Brexit">
<option value="Herefordshire">
<option value="Equalities and human rights">
<option value="Bradford">
<option value="Tourism, House of Lords reform, treasury, financial services and banking reform, energy">
<option value="South West London">
<option value="Developing Countries">
<option value="Professional regulation">
<option value="Tropical medicine">
<option value="Veterinary matters">
<option value="Isle of Islay">
<option value="Korea">
<option value="Global Investment Banking">
<option value="Innovation">
<option value="The North East">
<option value="The Americas">
<option value="Natural resources business sector">
<option value="Zambia">
<option value="Financial inclusion">
<option value="Heath and social care">
<option value="Children and family policy">
<option value="Poverty and disadvantage">
<option value="Business, industry and consumers: Economy and finance">
<option value="International affairs: Parliament, government and politics">
<option value="Chichester: West Sussex">
<option value="Women's economic empowerment">
<option value="Social Justice">
<option value="Tower Hamlets">
<option value="Global politics">
<option value="Regeneration">
<option value="Blackpool">
<option value="Business, industry and nationality">
<option value="Balkans">
<option value="Sub-Sahara Africa">
<option value="Education (HE)">
<option value="Scotland (especially Highlands and Islands)">
<option value="Arts"
<option value="End of life and assisted dying">
<option value="Humanism">
<option value="Middle East, especially Palestine">
<option value="Faith">
<option value="Kuwait">
<option value="Richmond">
<option value="Regional policy, education, training">
<option value="Eurasia">
<option value="Maritime matters">
<option value="Thames Estuary">
<option value="Nordic nations">
<option value="Falkland Islands and other South Atlantic dependencies">
<option value="Design and architecture">
<option value="Gypsies, Travellers and Roma.">
<option value="Nottingham.">
<option value="Argentina">
<option value="Germany, USA">
<option value="Economic policy, health, social security, education">
<option value="UK Regional Policy">
<option value="Housing, disability, health education, constitutional reform">
